# Generated by Django 3.0.7 on 2020-11-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genea_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
