# Generated by Django 3.0.7 on 2020-11-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genea_viewer', '0002_person_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
