# Generated by Django 3.0.7 on 2020-11-13 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genea_viewer', '0004_birthevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='genea_viewer.BirthEvent'),
        ),
    ]
