# Generated by Django 3.0.7 on 2020-11-13 23:58

from django.db import migrations, models
import django.db.models.deletion


def set_default_date_on_id_1(apps, schema_editor):
    LifeEvent = apps.get_model('genea_viewer', 'LifeEvent')
    default_life_event = LifeEvent.objects.get_or_create(id=1)
    BirthEvent = apps.get_model('genea_viewer', 'BirthEvent')
    BirthEvent.objects.get_or_create(id=1, defaults={'lifeevent_ptr_id': default_life_event[0].id})


class Migration(migrations.Migration):
    dependencies = [
        ('genea_viewer', '0005_person_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='genea_viewer.BirthEvent'),
        ),
        migrations.AlterField(
            model_name='birthevent',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(set_default_date_on_id_1),
    ]
