# Generated by Django 3.0.7 on 2021-04-30 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genea_viewer', '0006_auto_20201114_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeathEvent',
            fields=[
                ('lifeevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='genea_viewer.LifeEvent')),
            ],
            bases=('genea_viewer.lifeevent',),
        ),
        migrations.RemoveField(
            model_name='birthevent',
            name='date',
        ),
        migrations.AddField(
            model_name='lifeevent',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='backend_id',
            field=models.IntegerField(null=True),
        ),
    ]
