# Generated by Django 3.0.7 on 2021-04-30 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genea_viewer', '0007_auto_20210430_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='death_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='genea_viewer.DeathEvent'),
        ),
    ]
