# Generated by Django 3.0.7 on 2021-04-30 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genea_viewer', '0008_person_death_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='death_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='genea_viewer.DeathEvent'),
        ),
    ]
